export enum NotebookAction{
    GET_NOTEBOOK_START='GET_NOTEBOOK_START',
    GET_NOTEBOOK_SUCCESS='GET_NOTEBOOK_SUCCESS',
    GET_NOTEBOOK_FAILURE='GET_NOTEBOOK_FAILURE',

    POST_NOTEBOOK_START='POST_NOTEBOOK_START',
    POST_NOTEBOOK_SUCCESS='POST_NOTEBOOK_SUCCESS',
    POST_NOTEBOOK_FAILURE='POST_NOTEBOOK_FAILURE',

    DELETE_NOTEBOOK_START='DELETE_NOTEBOOK_START',
    DELETE_NOTEBOOK_SUCCESS='DELETE_NOTEBOOK_SUCCESS',
    DELETE_NOTEBOOK_FAILURE='DELETE_NOTEBOOK_FAILURE',

    PUT_NOTEBOOK_START='PUT_NOTEBOOK_START',
    PUT_NOTEBOOK_SUCCESS='PUT_NOTEBOOK_SUCCESS',
    PUT_NOTEBOOK_FAILURE='PUT_NOTEBOOK_FAILURE',

}

